services:
  app:
    restart: unless-stopped
    image: sumanchapai/gw:0.1
    environment:
      - GW_REPO=/data
      - GIT_USER_EMAIL=${GIT_USER_EMAIL}
      - GIT_USER_NAME=${GIT_USER_NAME}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_REPO=${GITHUB_REPO}
      - GITHUB_REPO_TOKEN=${GITHUB_REPO_TOKEN}
      - RESTRICTED_COMMANDS=${RESTRICTED_COMMANDS}
      - BACK_LINK=${BACK_LINK}
      - GIT_PAGE_TITLE=${TITLE}
      - HOST=${HOST}
    ports:
      - "${PORT}:8000"
    volumes:
      - ${GW_REPO}:/data
